name: upload experiment catalog
on: [workflow_dispatch]
jobs:
  experiment-catalog-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout work branch
        uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.8"
          architecture: "x64"
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel
      - id: cache-pipenv
        uses: actions/cache@v3
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
      - name: Install dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          pipenv install --dev
      - name: Convert catalog to JSON bundle
        run: |
          pipenv run python utils/data_processing/generate_experiment_bundle.py -p experiments/
          mkdir artifacts
          mv experiments-bundle.json artifacts
      - name: Upload catalog to S3
        uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          source_dir: 'artifacts'
          destination_dir: ''


