name: DOEDA validation
on: [pull_request]
jobs:
  yaml-schema-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: validate experiments folder files
        run: python utils/validation/scripts/validation.py
