name: DOEDA validation
on: [pull_request]
jobs:
  yaml-schema-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout work branch
        uses: actions/checkout@v3
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
          path: main
      - uses: actions/setup-python@v3
        with:
          python-version: "3.9"
          architecture: "x64"
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel
      - id: cache-pipenv
        uses: actions/cache@v3
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
      - name: Install dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          pipenv install --dev
      - name: validate experiments folder files
        run: pipenv run python utils/validation/scripts/validation.py
